import os
import ast

class CodeIndexer:
    def __init__(self, project_root):
        self.project_root = os.path.abspath(project_root)
        self.ignore_dirs = ['venv', '__pycache__', '.git', 'models', 'caleb_memory']
        self.index = {"files": {}}

    def scan_project(self):
        """Scans the repository, extracts AST signatures, and generates a map."""
        self.index["files"] = {}
        for root, dirs, files in os.walk(self.project_root):
            dirs[:] = [d for d in dirs if d not in self.ignore_dirs]
            for file in files:
                if file.endswith('.py'):
                    filepath = os.path.join(root, file)
                    self._analyze_python_file(filepath)
        self._generate_project_map()

    def _analyze_python_file(self, filepath):
        rel_path = os.path.relpath(filepath, self.project_root)
        try:
            with open(filepath, 'r', encoding='utf-8') as f:
                tree = ast.parse(f.read(), filename=filepath)
            
            classes = [node.name for node in ast.walk(tree) if isinstance(node, ast.ClassDef)]
            functions = [node.name for node in ast.walk(tree) if isinstance(node, ast.FunctionDef)]
            imports = [node.names[0].name for node in ast.walk(tree) if isinstance(node, ast.Import)]
            import_froms = [node.module for node in ast.walk(tree) if isinstance(node, ast.ImportFrom) and node.module]
            
            self.index["files"][rel_path] = {
                "classes": classes,
                "functions": functions,
                "dependencies": list(set(imports + import_froms))
            }
        except SyntaxError:
            self.index["files"][rel_path] = {"error": "Syntax Error during AST parsing."}
        except Exception as e:
            self.index["files"][rel_path] = {"error": str(e)}

    def _generate_project_map(self):
        """Writes the architecture to PROJECT_MAP.md per blueprint."""
        map_path = os.path.join(self.project_root, "PROJECT_MAP.md")
        with open(map_path, 'w', encoding='utf-8') as f:
            f.write("# CALEB Project Architecture Map\n\n")
            f.write("> Auto-generated by CodeIndexer. Updates on file changes.\n\n")
            for filepath, data in sorted(self.index["files"].items()):
                f.write(f"## `{filepath}`\n")
                if "error" in data:
                    f.write(f"- **[!] Error:** {data['error']}\n\n")
                    continue
                if data["classes"]: f.write(f"- **Classes:** {', '.join(data['classes'])}\n")
                if data["functions"]: f.write(f"- **Functions:** {', '.join(data['functions'])}\n")
                if data["dependencies"]: f.write(f"- **Dependencies:** {', '.join(data['dependencies'])}\n")
                f.write("\n")

if __name__ == "__main__":
    indexer = CodeIndexer(os.getcwd())
    indexer.scan_project()
    print("[+] Project map generated at PROJECT_MAP.md")
